l_english:
  custom_diff_strong_ger:0 "Strengthen Germany"
  custom_diff_strong_ita:0 "Strengthen Italy"
  custom_diff_strong_sov:0 "Strengthen Soviet"
  custom_diff_strong_fra:0 "Strengthen France"
  custom_diff_strong_eng:0 "Strengthen United Kingdom"
  custom_diff_strong_usa:0 "Strengthen USA"
  custom_diff_strong_jap:0 "Strengthen Japan"
  custom_diff_strong_chi:0 "Strengthen China"
  custom_diff_strong_afg:0 "Strengthen Afghanistan"
  custom_diff_strong_alb:0 "Strengthen Albania"
  custom_diff_strong_arg:0 "Strengthen Argentina"
  custom_diff_strong_ast:0 "Strengthen Australia"
  custom_diff_strong_aus:0 "Strengthen Austria"
  custom_diff_strong_bel:0 "Strengthen Belgium"
  custom_diff_strong_bhu:0 "Strengthen Bhutan"
  custom_diff_strong_bol:0 "Strengthen Bolivia"
  custom_diff_strong_bra:0 "Strengthen Brazil"
  custom_diff_strong_mal:0 "Strengthen British Malaya"
  custom_diff_strong_raj:0 "Strengthen British Raj"
  custom_diff_strong_bul:0 "Strengthen Bulgaria"
  custom_diff_strong_can:0 "Strengthen Canada"
  custom_diff_strong_chl:0 "Strengthen Chile"
  custom_diff_strong_col:0 "Strengthen Colombia"
  custom_diff_strong_cos:0 "Strengthen Costa Rica"
  custom_diff_strong_cub:0 "Strengthen Cuba"
  custom_diff_strong_cze:0 "Strengthen Czechoslovakia"
  custom_diff_strong_den:0 "Strengthen Denmark"
  custom_diff_strong_dom:0 "Strengthen Dominican"
  custom_diff_strong_ins:0 "Strengthen Dutch East Indies"
  custom_diff_strong_ecu:0 "Strengthen Ecuador"
  custom_diff_strong_els:0 "Strengthen El Salvador"
  custom_diff_strong_est:0 "Strengthen Estonia"
  custom_diff_strong_eth:0 "Strengthen Ethiopia"
  custom_diff_strong_fin:0 "Strengthen Finland"
  custom_diff_strong_gre:0 "Strengthen Greece"
  custom_diff_strong_gxc:0 "Strengthen Guanxi Clique"
  custom_diff_strong_gua:0 "Strengthen Guatemala"
  custom_diff_strong_hai:0 "Strengthen Haiti"
  custom_diff_strong_hon:0 "Strengthen Honduras"
  custom_diff_strong_hun:0 "Strengthen Hungary"
  custom_diff_strong_per:0 "Strengthen Iran"
  custom_diff_strong_irq:0 "Strengthen Iraq"
  custom_diff_strong_ire:0 "Strengthen Ireland"
  custom_diff_strong_lat:0 "Strengthen Latvia"
  custom_diff_strong_lib:0 "Strengthen Liberia"
  custom_diff_strong_lit:0 "Strengthen Lithuania"
  custom_diff_strong_lux:0 "Strengthen Luxembourg"
  custom_diff_strong_man:0 "Strengthen Manchukuo"
  custom_diff_strong_men:0 "Strengthen Mengkukuo"
  custom_diff_strong_mex:0 "Strengthen Mexico"
  custom_diff_strong_mon:0 "Strengthen Mongolia"
  custom_diff_strong_nep:0 "Strengthen Nepal"
  custom_diff_strong_hol:0 "Strengthen Netherlands"
  custom_diff_strong_nzl:0 "Strengthen New Zealand"
  custom_diff_strong_nic:0 "Strengthen Nicaragua"
  custom_diff_strong_nor:0 "Strengthen Norway"
  custom_diff_strong_oma:0 "Strengthen Oman"
  custom_diff_strong_pan:0 "Strengthen Panama"
  custom_diff_strong_par:0 "Strengthen Paraguay"
  custom_diff_strong_pru:0 "Strengthen Peru"
  custom_diff_strong_phi:0 "Strengthen Philippines"
  custom_diff_strong_pol:0 "Strengthen Poland"
  custom_diff_strong_por:0 "Strengthen Portugal"
  custom_diff_strong_rom:0 "Strengthen Romania"
  custom_diff_strong_sau:0 "Strengthen Saudi Arabia"
  custom_diff_strong_shx:0 "Strengthen Shanxi"
  custom_diff_strong_sia:0 "Strengthen Siam"
  custom_diff_strong_sik:0 "Strengthen Sinkiang"
  custom_diff_strong_saf:0 "Strengthen South Africa"
  custom_diff_strong_spr:0 "Strengthen Spain"
  custom_diff_strong_swe:0 "Strengthen Sweden"
  custom_diff_strong_swi:0 "Strengthen Switzerland"
  custom_diff_strong_tan:0 "Strengthen Tannu Tuva"
  custom_diff_strong_tib:0 "Strengthen Tibet"
  custom_diff_strong_tur:0 "Strengthen Turkey"
  custom_diff_strong_urg:0 "Strengthen Uruguay"
  custom_diff_strong_ven:0 "Strengthen Venezuela"
  custom_diff_strong_xsm:0 "Strengthen Xibei San Ma"
  custom_diff_strong_yem:0 "Strengthen Yemen"
  custom_diff_strong_yug:0 "Strengthen Yugoslavia"
  custom_diff_strong_yun:0 "Strengthen Yunnan"
  